language: python

python:
  - '3.8.2'

branches:
  only:
    - master

install:
  - pip install git+https://github.com/noaa-ocs-hydrography/kluster.git#egg=kluster
  - pip install --target=/home/travis/build/noaa-ocs-hydrography/kluster git+https://github.com/noaa-ocs-hydrography/drivers.git#egg=drivers

script: pytest tests
