language: python

python:
  - '3.8.2'

branches:
  only:
    - master

install:
  - pip install git+https://github.com/noaa-ocs-hydrography/kluster.git#egg=hstb.kluster
  - pip install git+https://github.com/noaa-ocs-hydrography/drivers.git#egg=hstb.drivers
  - pip install -r requirements.txt

script: pytest tests
