language: python

python:
  - '3.8.2'

branches:
  only:
    - master

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  
  # Useful for debugging any issues with conda
  - conda info -a
  
  - conda create -q -n test-environment python=3.8.2
  - conda activate test-environment
  - conda install -c conda-forge proj=7.0
  - conda install -c conda-forge proj-data
  - conda install -c conda-forge cartopy=0.17.0
  - pip install git+https://github.com/noaa-ocs-hydrography/kluster.git#egg=hstb.kluster
  - pip install -r requirements.txt

script: pytest tests
