name: build-and-test
on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # absolutely necessary to make conda activate work
    # Explained here: https://github.com/marketplace/actions/setup-miniconda#IMPORTANT
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # adds kluster repo files to $GITHUB_WORKSPACE in the VM's filesystem
      - uses: actions/checkout@v2

      # necessary to make conda activate work
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-environment
          python-version: 3.8.12

      - run: |
          conda install -c conda-forge qgis=3.18.3 vispy=0.9.4 pyside2=5.13.2 gdal=3.3.1 h5py
          conda install pytest six pytest-cov pytest-mock

      - run: |
          conda install git pip
          pip install git+https://github.com/noaa-ocs-hydrography/kluster.git#egg=hstb.kluster
      
      - run: pip install -r $GITHUB_WORKSPACE/requirements.txt
          
      # Run Tests
      - run: python -m pytest tests